### ISSUE TITLE
Failed to resolve import "./context/SubPage" from "frontend/App.tsx".

### ISSUE THREAD

**Issue by tuxy-streamer** [RajeshTechForge/pinac_workspace#82]
This shows that the errors are due to the use of wrong relative paths for import.
Output of ```npm run dev```:
```
npm run dev

> pinac-workspace@2.0.0 dev
> vite

vite v5.4.6 building for development...

watching for file changes...
vite v5.4.6 building for development...

watching for file changes...

  VITE v5.4.6  ready in 160 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

build started...

build started... (x2)
✓ 1 modules transformed.
dist-electron/preload.mjs  1.10 kB │ gzip: 0.38 kB
built in 68ms.
✓ 31 modules transformed.
dist-electron/main.js                         0.20 kB │ gzip:  0.16 kB
dist-electron/multipart-parser-Cf6GBRN-.js    9.99 kB │ gzip:  2.52 kB
dist-electron/main-BRMwNM7o.js              345.53 kB │ gzip: 67.22 kB
built in 518ms.
[140706:0925/214625.550641:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[140706:0925/214625.550680:ERROR:select_file_dialog_linux_portal.cc(290)] Failed to read portal version property
9:46:25 PM [vite] Internal server error: Failed to resolve import "./context/SubPage" from "frontend/App.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /storage/projects/worktrees/pinac-workspace/session-delete/frontend/App.tsx:8:32
  23 |  import { ThemeModeContext } from "./context/ThemeMode";
  24 |  import { ThemeStyleContext } from "./context/ThemeStyle";
  25 |  import { SubPageProvider } from "./context/SubPage";
     |                                   ^
  26 |  import { WelcomeTextProvider } from "./context/WelcomeText";
  27 |  import { ChatMsgProvider } from "./context/ChatMsg";
      at TransformPluginContext._formatError (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49192:41)
      at TransformPluginContext.error (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49187:16)
      at normalizeUrl (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:63983:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:64115:39
      at async Promise.all (index 10)
      at async TransformPluginContext.transform (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:64042:7)
      at async PluginContainer.transform (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49033:18)
      at async loadAndTransform (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:51866:27)
9:46:25 PM [vite] Pre-transform error: Failed to resolve import "./context/SubPage" from "frontend/App.tsx". Does the file exist?
9:46:25 PM [vite] Pre-transform error: Failed to resolve import "../context/SubPage" from "frontend/components/Sidebar.tsx". Does the file exist?
9:46:25 PM [vite] Pre-transform error: Failed to resolve import "../context/SubPage" from "frontend/components/Sidebar.tsx". Does the file exist? (x2)
9:46:25 PM [vite] Pre-transform error: Failed to resolve import "../context/SubPage" from "frontend/pages/Home.tsx". Does the file exist?
9:46:26 PM [vite] Pre-transform error: Failed to resolve import "../../context/SubPage" from "frontend/features/header/index.tsx". Does the file exist?
9:46:26 PM [vite] Pre-transform error: Failed to resolve import "../../context/SubPage" from "frontend/features/header/index.tsx". Does the file exist? (x2)
9:46:26 PM [vite] Pre-transform error: Failed to resolve import "../../context/SubPage" from "frontend/features/header/index.tsx". Does the file exist? (x3)
9:46:26 PM [vite] Pre-transform error: Failed to resolve import "../../context/SubPage" from "frontend/features/header/index.tsx". Does the file exist? (x4)
9:46:26 PM [vite] Pre-transform error: Failed to resolve import "../../context/SubPage" from "frontend/features/header/index.tsx". Does the file exist? (x5)
9:46:30 PM [vite] Internal server error: Failed to resolve import "./context/SubPage" from "frontend/App.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /storage/projects/worktrees/pinac-workspace/session-delete/frontend/App.tsx:8:32
  23 |  import { ThemeModeContext } from "./context/ThemeMode";
  24 |  import { ThemeStyleContext } from "./context/ThemeStyle";
  25 |  import { SubPageProvider } from "./context/SubPage";
     |                                   ^
  26 |  import { WelcomeTextProvider } from "./context/WelcomeText";
  27 |  import { ChatMsgProvider } from "./context/ChatMsg";
      at TransformPluginContext._formatError (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49192:41)
      at TransformPluginContext.error (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49187:16)
      at normalizeUrl (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:63983:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:64115:39
      at async Promise.all (index 10)
      at async TransformPluginContext.transform (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:64042:7)
      at async PluginContainer.transform (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49033:18)
      at async loadAndTransform (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:51866:27)
      at async viteTransformMiddleware (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:61823:24)
9:46:30 PM [vite] Pre-transform error: Failed to resolve import "../context/SubPage" from "frontend/pages/Home.tsx". Does the file exist?
9:46:30 PM [vite] Pre-transform error: Failed to resolve import "../context/SubPage" from "frontend/components/Sidebar.tsx". Does the file exist?
9:46:30 PM [vite] Pre-transform error: Failed to resolve import "../context/SubPage" from "frontend/components/Sidebar.tsx". Does the file exist? (x2)
9:46:30 PM [vite] Pre-transform error: Failed to resolve import "../../context/SubPage" from "frontend/features/header/index.tsx". Does the file exist?
9:46:33 PM [vite] Internal server error: Failed to resolve import "./context/SubPage" from "frontend/App.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /storage/projects/worktrees/pinac-workspace/session-delete/frontend/App.tsx:8:32
  23 |  import { ThemeModeContext } from "./context/ThemeMode";
  24 |  import { ThemeStyleContext } from "./context/ThemeStyle";
  25 |  import { SubPageProvider } from "./context/SubPage";
     |                                   ^
  26 |  import { WelcomeTextProvider } from "./context/WelcomeText";
  27 |  import { ChatMsgProvider } from "./context/ChatMsg";
      at TransformPluginContext._formatError (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49192:41)
      at TransformPluginContext.error (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49187:16)
      at normalizeUrl (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:63983:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:64115:39
      at async Promise.all (index 10)
      at async TransformPluginContext.transform (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:64042:7)
      at async PluginContainer.transform (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:49033:18)
      at async loadAndTransform (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:51866:27)
      at async viteTransformMiddleware (file:///storage/projects/worktrees/pinac-workspace/session-delete/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:61823:24)
9:46:33 PM [vite] Pre-transform error: Failed to resolve import "../context/SubPage" from "frontend/pages/Home.tsx". Does the file exist?
9:46:33 PM [vite] Pre-transform error: Failed to resolve import "../context/SubPage" from "frontend/components/Sidebar.tsx". Does the file exist?
9:46:33 PM [vite] Pre-transform error: Failed to resolve import "../context/SubPage" from "frontend/components/Sidebar.tsx". Does the file exist? (x2)
9:46:33 PM [vite] Pre-transform error: Failed to resolve import "../../context/SubPage" from "frontend/features/header/index.tsx". Does the file exist?
```

**Comment by RajeshTechForge** [comment]
Hello @subhamc88 I cannot work on this error, because I am not getting any kind of error, and the file path in the code is also correct. Can you please tell me your OS ?

(Once check if you have accidentally deleted any file)

**Comment by tuxy-streamer** [comment]
I cloned it, then did a ```npm i``` and then ran the project.
I'm using arch linux.
Is this an operating system issue ?

**Comment by RajeshTechForge** [comment]
> I cloned it, then did a ```npm i``` and then ran the project.
> I'm using arch linux.
> Is this an operating system issue ?
> 

This project is tested on Kali & Ubuntu Linux. I can't assure you about Arch Linux. Although it looks like a missing file error.

**Comment by RajeshTechForge** [comment]
> I cloned it, then did a ```npm i``` and then ran the project.
> I'm using arch linux.
> Is this an operating system issue ?
> 

I found the issue. It's regarding the file name of `SubPage.tsx`. I will fix it soon.

**Comment by RajeshTechForge** [comment]
Hi @subhamc88, I believe the error has been resolved. Please try recloning once again.

**Comment by subhamc88** [comment]
Yup, it's fixed.

**Comment by tuxy-streamer** [comment]
Yup, it's done.
